# Basic Python

## 1. Split this string

In [ ]:
s = "Hi there Sam!"

In [2]:
s1 = "Hi there Sam!"
print(s1.split())

['Hi', 'there', 'Sam!']


*`italicized text`*## 2. Use .format() to print the following string. 

### Output should be: The diameter of Earth is 12742 kilometers.

In [ ]:
planet = "Earth"
diameter = 12742

In [3]:
planet = "Earth"
diameter = 12742
print("The diameter of Earth is {} kilometers".format(diameter))

The diameter of Earth is 12742 kilometers


## 3. In this nest dictionary grab the word "hello"

In [ ]:
d = {'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'hello']}]}]}

In [6]:
d = {'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'hello']}]}]}
print(d['k1'][3]['tricky'][3]['target'][3])

hello


# Numpy

In [ ]:
import numpy as np

## 4.1 Create an array of 10 zeros? 
## 4.2 Create an array of 10 fives?

In [9]:
array = [0]*10
print(array)

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]


In [10]:
array = [5]*10
print(array)

[5, 5, 5, 5, 5, 5, 5, 5, 5, 5]


## 5. Create an array of all the even integers from 20 to 35

In [11]:
array = []
for num in range(20,36,2):
  array.append(num)
print(array)

[20, 22, 24, 26, 28, 30, 32, 34]


## 6. Create a 3x3 matrix with values ranging from 0 to 8

In [12]:
import numpy as np
array = np.arange(0,9).reshape((3,3))
print(array)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


## 7. Concatinate a and b 
## a = np.array([1, 2, 3]), b = np.array([4, 5, 6])

In [15]:
import numpy as np
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
print(np.concatenate([a,b]))

[1 2 3 4 5 6]


# Pandas

## 8. Create a dataframe with 3 rows and 2 columns

In [ ]:
import pandas as pd


In [17]:
import pandas as pd
data = {'Name':['Raam', 'Shyam', 'Sethu'],
        'Qualification':['BE',  'MCA', 'MBA']}
  
df = pd.DataFrame(data)
  
print(df)

    Name Qualification
0   Raam            BE
1  Shyam           MCA
2  Sethu           MBA


## 9. Generate the series of dates from 1st Jan, 2023 to 10th Feb, 2023

In [19]:
import pandas as pd
dates = pd.date_range('2023-01-01', periods=5, freq='D')
s = pd.Series(dates)
print(s)

0   2023-01-01
1   2023-01-02
2   2023-01-03
3   2023-01-04
4   2023-01-05
dtype: datetime64[ns]


## 10. Create 2D list to DataFrame

lists = [[1, 'aaa', 22],
         [2, 'bbb', 25],
         [3, 'ccc', 24]]

In [ ]:
lists = [[1, 'aaa', 22], [2, 'bbb', 25], [3, 'ccc', 24]]

In [20]:
import pandas as pd
lists = [[1, 'aaa', 22], [2, 'bbb', 25], [3, 'ccc', 24]]
df = pd.DataFrame( ['points', 'rebounds']) 
print(df )

          0
0    points
1  rebounds
